### ISSUE TITLE
可否 dns 和 proxy 的 地址和端口可修改？

### ISSUE THREAD

**Issue by laincat** [Mitsuhaxy/luci-app-miniproxy#2]
想说用局域网或者其它网络的？

**Comment by Mitsuhaxy** [comment]
这个小插件不涉及dns哈。
如果想修改端口请使用b3.0分支，这个版本包含luci界面。

**Comment by Mitsuhaxy** [comment]
https://github.com/Mitsuhaxy/luci-app-tproxy/releases/tag/3.7

**Comment by laincat** [comment]
我想丢到 nas/其它docker的clash去，哈哈哈，因为原来是用ssrp感觉“太复杂”。

路由全部丢给“192.168.x.x:7890”，dns也是一样。然后某几台设备直通（自带软件）。
